
hulib.o: hulib.h hulib.cpp
  g++ -g -c hulib.cpp

gen_table.o: hulib.h gen_table.cpp
  g++ -g -c gen_table.cpp

gen_table: gen_table.o hulib.o
  g++ -o gen_table gen_table.o hulib.o

clean:
  rm *.o
  rm gen_table
